---
title: "Curriculum Vitae"
format:
  html:
    toc: true
  pdf:
    author: Aryaman Suri
format-links: [pdf]
---


## EDUCATION

### Bachelor of Science -- Computer Science and Statistics
***University of Toronto*** [*Sept 2019 --- Present*]{.cvdate}

-	Bachelor of Science in Computer Science & Statistics; minor in Mathematics 
-	Received the University of Toronto International Scholar Award

Relevant Coursework: Machine Learning, Programming Languages & Compilers, Data Structures, Algorithms & Models of Computation, Algebraic Cryptography, Computer Architecture, Computer Systems, Database Systems, Numerical Methods, Statistical Modeling, Computational Statistics, Multivariable Calculus, Differential Equations


## WORK EXPERIENCE{style="page-break-before: always"}

### Language Education Research Assistant

***University of Toronto Mississauga*** [Jan 2024 -- Present]{.cvdate}

The language studies lab at the University of Toronto Mississauga is a dedicated research hub exploring language acquisition, cognitive processes, and socio-cultural influences on linguistic development.

-	Conducted comprehensive research on language education benefits and challenges, referencing authoritative sources.
-	Analyzed statistical data to identify trends in language course enrollments, contributing to the understanding of attrition.
-	Formulated research questions and methodologies to investigate student and instructor beliefs in language learning.
-	Led data collection efforts, including surveys and interviews, to gather insights into student motivations for language course participation.

### Freelance Data Analyst

***Telus International*** [Nov 2023 -- Present]{.cvdate}

Telus International has an AI training platform that works on increasing the performance of Al chatbots by
providing the training they need to understand and interact with real world users.

-	Lead and contribute to the crucial field of data quality within machine learning, meticulously labeling,
ranking, auditing, and correcting data to ensure optimal accuracy in our models.
-	Completed text-based tasks, ensuring every piece of information enhances the overall quality of the
data ecosystem.
-	Proactively recommended enhancements to elevate the data quality standards and contribute to the
continuous improvement of processes.
-	Provided constructive feedback to cross-functional team members, fostering a culture of excellence within interdisciplinary teams.

### Data Scienctist

***CulturaliQ*** [May 2022 -- Sept 2022]{.cvdate}

CultureIQ is a market research company focused on data analytics to help clients better reach a more diverse customer base

-	Managed end to end data analytics pipeline including collection, cleaning, exploration, and analysis
-	Enhanced database connectivity by leveraging software development expertise in Python NumPy, SciPy, python-twitter and MySQL db.
-	Developed and implemented statistical models to analyze the behaviors of different demographic groups and provided clients detailed analysis to improve targeted marketing
-	Designed web surveys that improved overall data collection and accuracy rates by 20%

### Software Developer

***ICICI Securities*** [May 2021 -- Sept 2021]{.cvdate}

ICICI securities is a subsidiary of the ICICI Bank built to provide financial solutions to over 5 million global customers. It allows customers to share trade at a low brokerage.

-	Administered internal databases in MERN stack, used React.js and SQL Server for maintenance
-	Launched an in-house platform that automates end-to-end process to store and update tax invoices that was previously manually handled by employees.

### Researcher

***The WhiteBoard Company*** [May 2018 -- July 2018]{.cvdate}

TWC is a 360-firm specializing in interactive digital solutions, branding, and events with cumulative experience of over 80 years in diverse industry sectors.

-	Leveraged knowledge on SEO and interactive digital solutions to execute social media business strategy and improved digital audience engagement 
-	Implemented full-stack marketing solutions for clients by utilizing UI design and mobile app development 

# Technical Skills

## Languages
Python, Pandas, SQL, MySQL, PostgreSQL, Shell, R, Java, JavaScript

## Strengths
Backend systems design, web development, predictive modeling
